package com.arvato.thoroughly.model;

import com.google.gson.annotations.Expose;

import java.util.Date;

public class JdpTbTrade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.tid
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    @Expose
    private Long tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.status
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    @Expose
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.type
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    @Expose
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.seller_nick
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    @Expose
    private String sellerNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.buyer_nick
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    @Expose
    private String buyerNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.created
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    @Expose
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.modified
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    @Expose
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.jdp_hashcode
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    @Expose
    private String jdpHashcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.jdp_created
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    @Expose
    private Date jdpCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.jdp_modified
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    @Expose
    private Date jdpModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdp_tb_trade.jdp_response
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    @Expose
    private String jdpResponse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.tid
     *
     * @return the value of jdp_tb_trade.tid
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.tid
     *
     * @param tid the value for jdp_tb_trade.tid
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.status
     *
     * @return the value of jdp_tb_trade.status
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.status
     *
     * @param status the value for jdp_tb_trade.status
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.type
     *
     * @return the value of jdp_tb_trade.type
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.type
     *
     * @param type the value for jdp_tb_trade.type
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.seller_nick
     *
     * @return the value of jdp_tb_trade.seller_nick
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public String getSellerNick() {
        return sellerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.seller_nick
     *
     * @param sellerNick the value for jdp_tb_trade.seller_nick
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public void setSellerNick(String sellerNick) {
        this.sellerNick = sellerNick == null ? null : sellerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.buyer_nick
     *
     * @return the value of jdp_tb_trade.buyer_nick
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.buyer_nick
     *
     * @param buyerNick the value for jdp_tb_trade.buyer_nick
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick == null ? null : buyerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.created
     *
     * @return the value of jdp_tb_trade.created
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.created
     *
     * @param created the value for jdp_tb_trade.created
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.modified
     *
     * @return the value of jdp_tb_trade.modified
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.modified
     *
     * @param modified the value for jdp_tb_trade.modified
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.jdp_hashcode
     *
     * @return the value of jdp_tb_trade.jdp_hashcode
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public String getJdpHashcode() {
        return jdpHashcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.jdp_hashcode
     *
     * @param jdpHashcode the value for jdp_tb_trade.jdp_hashcode
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public void setJdpHashcode(String jdpHashcode) {
        this.jdpHashcode = jdpHashcode == null ? null : jdpHashcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.jdp_created
     *
     * @return the value of jdp_tb_trade.jdp_created
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public Date getJdpCreated() {
        return jdpCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.jdp_created
     *
     * @param jdpCreated the value for jdp_tb_trade.jdp_created
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public void setJdpCreated(Date jdpCreated) {
        this.jdpCreated = jdpCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.jdp_modified
     *
     * @return the value of jdp_tb_trade.jdp_modified
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public Date getJdpModified() {
        return jdpModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.jdp_modified
     *
     * @param jdpModified the value for jdp_tb_trade.jdp_modified
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public void setJdpModified(Date jdpModified) {
        this.jdpModified = jdpModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdp_tb_trade.jdp_response
     *
     * @return the value of jdp_tb_trade.jdp_response
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public String getJdpResponse() {
        return jdpResponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdp_tb_trade.jdp_response
     *
     * @param jdpResponse the value for jdp_tb_trade.jdp_response
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    public void setJdpResponse(String jdpResponse) {
        this.jdpResponse = jdpResponse == null ? null : jdpResponse.trim();
    }
}
