package com.arvato.thoroughly.dao;

import com.arvato.thoroughly.model.JdpTbRefund;


public interface JdpTbRefundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_refund
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    int deleteByPrimaryKey(Long refundId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_refund
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    int insert(JdpTbRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_refund
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    int insertSelective(JdpTbRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_refund
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    JdpTbRefund selectByPrimaryKey(Long refundId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_refund
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    int updateByPrimaryKeySelective(JdpTbRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_refund
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(JdpTbRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_refund
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    int updateByPrimaryKey(JdpTbRefund record);
}
