package com.arvato.thoroughly.dao;

import com.arvato.thoroughly.model.JdpTbTrade;

import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;


public interface JdpTbTradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    int deleteByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    int insert(JdpTbTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    int insertSelective(JdpTbTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    JdpTbTrade selectByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    int updateByPrimaryKeySelective(JdpTbTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(JdpTbTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdp_tb_trade
     *
     * @mbggenerated Tue Oct 25 20:18:36 CST 2016
     */
    int updateByPrimaryKey(JdpTbTrade record);


    List<JdpTbTrade> selectByModify(@Param("start") Date start,@Param("end") Date end);
}
